// Code generated by "stringer -type=ReferenceMatch -output=reference_match_string_gen.go"; DO NOT EDIT.

package model

import "fmt"

const _ReferenceMatch_name = "ReferenceMatchNoneReferenceMatchFullReferenceMatchPartialReferenceMatchSimple"

var _ReferenceMatch_index = [...]uint8{0, 18, 36, 57, 77}

func (i ReferenceMatch) String() string {
	if i < 0 || i >= ReferenceMatch(len(_ReferenceMatch_index)-1) {
		return fmt.Sprintf("ReferenceMatch(%d)", i)
	}
	return _ReferenceMatch_name[_ReferenceMatch_index[i]:_ReferenceMatch_index[i+1]]
}
